---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: Flag1

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.distinct_id
          operator: in-array
          operands:
            - '  '
    flagValue: false
  - allOf:
      - property:
          name: rox.platform
          operator: in-array
          operands:
            - '  '
    flagValue: false
